# Generated by Django 4.2.5 on 2023-11-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
